spring:
  application:
    name: PatientManager
    env: dev

  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      base-path: /gerimedica
      exposure:
        include: health
server:
  port: 9090
  undertow:
    io-threads: 200
    worker-threads: 250

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    filter: true
  packages-to-scan: nl.gerimedica.assignment
  paths-to-match: /api/**